### ISSUE TITLE
Would it be possible to add a camelCase option for the generated keys?

### ISSUE THREAD

**Issue by lineablepatrice** [bratan/flutter_translate_gen#4]
Hello, thanks for the library, very cool.

I see that dart_casing allow camelCase as an option, would it be possible to add the to this generator too?

Thanks a lot!

**Comment by MlecznyU** [comment]
That would be great, right now I use lint package and I got a lot of errors 
![Capture](https://user-images.githubusercontent.com/59980382/86496394-91a08800-bd7d-11ea-9444-72c7fde23e71.PNG)

**Comment by bratan** [comment]
Hello, I will implement the option in the next couple of days.
